services:
  - type: web
    name: wedding-template
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /*
        name: Permissions-Policy
        value: autoplay=*
    routes:
      - type: rewrite
        source: /*
        destination: /index.html